version: '3.9'
services:
  postgres:
    container_name: postgres_patient
    image: postgres:14.2-alpine3.15
    ports:
      - 5432:5432
    volumes:
      - pg_patient:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
volumes:
  pg_patient: